### PR TITLE
Add BitKeep Wallet

### PR DESCRIPTION
**Pull request by bitkeepos**

### CODE REVIEW

**Comment by bitkeepos** [comment]
How about this pull?
BitKeep have released Terra and Terra DApp. You can try it: https://bitkeep.com

**Comment by bitkeepos** [comment]
Please check it.

**Comment by bitkeepos** [comment]
Hello, please handle this, thanks very much.

**Comment by Jared-TFL** [comment]
Cannot add Luna, or Terra network on mobile IOS 14.7.1
Tag me when updated.

**Comment by Jared-TFL** [comment]
Was able to add.
Request UI include Terra as a default chain.
@bitkeepwallet

**Pull request closed without merging**
