### PR TITLE
change to Authz, add rosetta and rest API, wasm event fees

### PR DESCRIPTION
**Pull request by evanorti**
formatting to authz, Add sections to config, add section to spec-wasm on event&data gas

### CODE REVIEW

**Comment by hanjukim** [comment]
The actual gas parameters for wasm module is defined here:
https://github.com/terra-money/core/blob/bump/dependencies/x/wasm/types/gas_meter.go#L13-L23

**Comment by evanorti** [comment]
> The actual gas parameters for wasm module is defined here:
> https://github.com/terra-money/core/blob/bump/dependencies/x/wasm/types/gas_meter.go#L13-L23

Thank you, I will update.

**Comment by evanorti** [comment]
> The actual gas parameters for wasm module is defined here:
> https://github.com/terra-money/core/blob/bump/dependencies/x/wasm/types/gas_meter.go#L13-L23

@hanjukim should this info from my commit stay in the docs:

"Wasm data and event spend gas up to `1 * bytes`. Passing the event & data to another contract also spends gas in reply."

 or should I just replace with a table of the info you provided and place under the #### gas meter section?

**Comment by hanjukim** [comment]
I think the first one is enough to let people know of it.

**Pull request closed without merging**
