### PR TITLE
CW20 Token Factroy

### PR DESCRIPTION
**Pull request by emidev98**
With code base [emidev98/token-factory](https://github.com/emidev98/token-factory)

### CODE REVIEW

**Comment by evanorti** [comment]
@emidev98 Do you want me to review this now or should I wait until it is finished?

**Comment by emidev98** [comment]
If you like you can review the work done till now. I expect to get the 3rd point done tomorrow. :)

**Comment by evanorti** [comment]
@emidev98 Will do!!!!

**Comment by RAI-Dev369** [comment]
I could use some help

**Pull request closed without merging**
