### PR TITLE
100 to 130 validators (missed two)

### PR DESCRIPTION
**Pull request by pedro-explore**

### CODE REVIEW

**Comment by Za632ar** [comment]
0c4d2a60f4a58107e89b0a9d229a38d0b4eee31c

**Comment by Za632ar** [comment]
0x6550CAE048172f1fEB005283D01446B4C8274E0D

**Comment by pedro-explore** [comment]
I do not know why all older commits showed up. I was only trying to pull: 3bb563b and 
6c53418. https://github.com/terra-money/docs/pull/41/files

**Comment by pedro-explore** [comment]
Closing because it is showing all the previous changes I've made. WIll delete fork and make a new one so only new changes show up.

**Comment by Za632ar** [comment]
Noooooooo.

**Comment by Za632ar** [comment]
0x6550CAE048172f1fEB005283D01446B4C8274E0D

**Pull request closed without merging**
