### PR TITLE
Running-a-full-node how-to rework

### PR DESCRIPTION
**Pull request by rtviii**

### CODE REVIEW

**Comment by rtviii** [comment]
@Jared-Warn @octalmage

**Comment by alecande11** [comment]
@rtviii for the terrad config folder structure
```bash
~/.terra/config
│-- addrbook.json                       # a registry of peers to connect to
│-- app.toml                            # terrad configuration file
│-- client.toml                         #  configurations for the cli wallet (ex terracli)
│-- config.toml                         # Tendermint configuration  file
│-- genesis.json                        # gensesis transactions
# terrad does not create or use a gentx folder if you are joining a public network
# └─── gentx
#     └ gentx-9dd77b79daf841e0bbb4306e93d4b01c7cdf3997.json
│-- node_key.json                       # private key used for node authentication in the p2p protocol (it's corresponding public key is the nodeid)
└-- priv_validator_key.json             # key used by the validator on the node to sign blocks
```

**Comment by Jared-TFL** [comment]
This looks good @rtviii. There are some errors that prevent merging. After those are fixed up, and @octalmage approves you can make the merge.

**Comment by rtviii** [comment]
👀 https://github.com/terra-money/docs/pull/232

**Pull request closed without merging**
