### PR TITLE
feat(token-facotry): version 2 upgraded

### PR DESCRIPTION
**Pull request by emidev98**
Guide for token factory updated according to the updates applied to https://github.com/emidev98/token-factory for Terra V2 compatibility.

### CODE REVIEW

**Comment by TunaMoney** [comment]
"Response: unable to resolve type URL /terra.wasm.v1beta1.MsgStoreCode: tx parse error: invalid request" on deployment is this issue also rectified in the updates? updated localterra and core but doesnt seem to resolve the issue. kindly advise. thanks.

**Comment by evanorti** [comment]
> "Response: unable to resolve type URL /terra.wasm.v1beta1.MsgStoreCode: tx parse error: invalid request" on deployment is this issue also rectified in the updates? updated localterra and core but doesnt seem to resolve the issue. kindly advise. thanks.

@emidev98

**Comment by emidev98** [comment]
Hey @TunaMoney , what version of terrain are you using?

**Comment by TunaMoney** [comment]
@terra-money/terrain/0.2.0 wsl-x64 node-v16.13.0

**Comment by TunaMoney** [comment]
> Hey @TunaMoney , what version of terrain are you using?

@terra-money/terrain/0.2.0 wsl-x64 node-v16.13.0

**Comment by TunaMoney** [comment]
oh looks like there was an update. i was referring to the wrong package. fml 

> > Hey @TunaMoney , what version of terrain are you using?
> 
> @terra-money/terrain/0.2.0 wsl-x64 node-v16.13.0

**Comment by emidev98** [comment]
@TunaMoney update the package to the 0.3.1 version please

**Comment by TunaMoney** [comment]
@emidev98 

doesn't seem to support deployment on terra classic now unless i rollback to terrain 0.2.0 ?  Does seem like support for "allow_interface_version_7 " is supported? 
image


> Response: failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see
>     https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): store wasm contract failed: invalid request

**Comment by emidev98** [comment]
Hey @TunaMoney , I have not tried to deploy with terrain 0.3.1 to Terra Classic, but you can rollback to the version of terrain 0.2.0 which should work fine with Terra Classic.

**Comment by TunaMoney** [comment]
sure. its a solution for now. thanks.

**Pull request merged**
